name = "Radiant"
uuid = "b26cd056-4456-4d61-8550-65e4ff5b9100"
authors = ["Charles Bienvenue"]
version = "1.1.11"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
JLD2 = "0.4, 0.5"
SpecialFunctions = "2.6.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
